#!/bin/bash -x
# Original shell script from  https://github.com/iiab/iiab-factory/blob/master/curl-me
# Start loading IIAB. "bash -x" is debug mode
set -e
export DEBIAN_FRONTEND=noninteractive
apt-get install -y git wget sed

sed -i 's|[#]*PasswordAuthentication no|PasswordAuthentication yes|g' /etc/ssh/sshd_config
systemctl daemon-reload
systemctl reload sshd

mkdir -p /opt/iiab
cd /opt/iiab
# Get the extras
# This curl-me script should live here:
git clone https://github.com/iiab/iiab-factory --depth 1
# Get the current install options (we'll do more with these later like manage releases)
#source /opt/iiab/iiab-factory/factory-settings

#git clone https://github.com/tim-moody/iiab-admin-console -b fixes-oct-24
git clone https://github.com/iiab/iiab-admin-console --depth 1

git clone https://github.com/iiab/iiab-menu --depth 1

# Get iiab
#git clone https://github.com/jvonau/iiab -b iiab-install4
git clone https://github.com/jvonau/iiab -b net-merge

cd /opt/iiab/iiab/vars
wget http://download.iiab.io/6.5/rpi/local_vars_big.yml
mv local_vars_big.yml local_vars.yml
echo "openvpn_enabled: True" >> local_vars.yml
#echo "moodle_install: False" >> local_vars.yml
#echo "moodle_enabled: False" >> local_vars.yml
#echo "is_VM: True" >> local_vars.yml
echo "no_net_restart: True" >> local_vars.yml

cd /opt/iiab/iiab
./scripts/ansible
#./runansible
./iiab-install

cd /opt/iiab/iiab-admin-console
./install

cd /opt/iiab/iiab-menu
./cp-menus

iiab-remote-on
cat /etc/iiab/iiab.ini
ip a
sleep 7200
