#!/bin/bash -x
# Original shell script from  https://github.com/iiab/iiab-factory/blob/master/curl-me
# Start loading IIAB. "bash -x" is debug mode

set -e
yum install -y git wget sed

sed -i 's|[#]*PasswordAuthentication no|PasswordAuthentication yes|g' /etc/ssh/sshd_config
systemctl daemon-reload
systemctl reload sshd

mkdir -p /opt/iiab

# Get the extras
cd /opt/iiab
git clone https://github.com/iiab/iiab-factory --depth 1

# Get the current install options (we'll do more with these later like manage releases)
#source /opt/iiab/iiab-factory/factory-settings

git clone https://github.com/tim-moody/iiab-admin-console -b fixes-oct-24
#https://github.com/iiab/iiab-admin-console --depth 1

git clone https://github.com/iiab/iiab-menu --depth 1

# Get iiab
#git clone https://github.com/jvonau/iiab -b iiab-stage2
#git clone https://github.com/jvonau/iiab -b PSA
git clone https://github.com/iiab/iiab -b master --depth 1

cd /opt/iiab/iiab/
#./scripts/ansible

cd /opt/iiab/iiab/vars
#wget http://download.iiab.io/6.5/rpi/local_vars_min.yml
#mv local_vars_min.yml local_vars.yml
wget http://download.iiab.io/6.5/rpi/local_vars_big.yml
mv local_vars_big.yml local_vars.yml

echo "calibre_enabled: False" >> local_vars.yml
echo "awstats_enabled: False" >> local_vars.yml
echo "osm_enabled: False" >> local_vars.yml
echo "openvpn_enabled: True" >> local_vars.yml
echo "installing: True" >> local_vars.yml
echo "is_VM: True" >> local_vars.yml
cd /opt/iiab/iiab

#./runansible
./iiab-install

cd /opt/iiab/iiab-admin-console
./install

cd /opt/iiab/iiab-menu
./cp-menus
iiab-remote-on
cat /etc/iiab/iiab.ini
# let see if poking via vpn is possible
ip a
sleep 7200
